server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true  # Обязательно для YouTube

  plugins:
    lavasrc:
      providers:
        - "ytsearch:%QUERY%"  # Поиск по названию на YouTube
        - "scsearch:%QUERY%"  # Опционально для SoundCloud
        - "ytsearch:\"%ISRC%\" fallback"  # Опционально для лучшего fallback

metrics:
  enabled: false

sentry:
  dsn: ""